name: A workflow for my Hello World file
on: push
env:
 NORUN: true
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "JP"
  test:
    name: job2
    runs-on: ubuntu-latest
    steps:
       - run: echo "norun $NORUN"
#      - run: echo "Norun: $NORUN"
      
