name: Test sched

on: 
  schedule:
    - cron: "0/15 2 3 * *"
    
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List
        run: |
          pwd
          ls -a
          
